// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AutoLoadHardware() {
  return window['go']['backend']['App']['AutoLoadHardware']();
}

export function ConfirmClose() {
  return window['go']['backend']['App']['ConfirmClose']();
}

export function GenerateSTFiles(arg1) {
  return window['go']['backend']['App']['GenerateSTFiles'](arg1);
}

export function ImportHardwareConfig() {
  return window['go']['backend']['App']['ImportHardwareConfig']();
}

export function Startup(arg1) {
  return window['go']['backend']['App']['Startup'](arg1);
}
