// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConfirmClose() {
  return window['go']['backend']['App']['ConfirmClose']();
}

export function Startup(arg1) {
  return window['go']['backend']['App']['Startup'](arg1);
}
