// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConfirmClose() {
  return window['go']['backend']['App']['ConfirmClose']();
}

export function ExportEVToST(arg1) {
  return window['go']['backend']['App']['ExportEVToST'](arg1);
}

export function LoadData() {
  return window['go']['backend']['App']['LoadData']();
}

export function SaveData(arg1) {
  return window['go']['backend']['App']['SaveData'](arg1);
}
