// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function ConfirmClose():Promise<void>;

export function ExportEVToST(arg1:Array<backend.Electrovalve>):Promise<void>;

export function LoadData():Promise<backend.AppData>;

export function SaveData(arg1:backend.AppData):Promise<void>;
