// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetEquipmentFieldSections() {
  return window['go']['registry']['Service']['GetEquipmentFieldSections']();
}

export function GetEquipmentRegistry() {
  return window['go']['registry']['Service']['GetEquipmentRegistry']();
}

export function GetPageRegistry() {
  return window['go']['registry']['Service']['GetPageRegistry']();
}
