// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {registry} from '../models';

export function GetEquipmentFieldSections():Promise<Array<registry.EquipmentFieldSection>>;

export function GetEquipmentRegistry():Promise<Record<string, registry.EquipmentDefinition>>;

export function GetPageRegistry():Promise<Record<string, registry.PageDefinition>>;
