// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function HasRobotVarIndexError(arg1, arg2) {
  return window['go']['services']['CalculationService']['HasRobotVarIndexError'](arg1, arg2);
}

export function IsConfigFieldVisible(arg1, arg2, arg3) {
  return window['go']['services']['CalculationService']['IsConfigFieldVisible'](arg1, arg2, arg3);
}

export function IsRobotSelected(arg1, arg2) {
  return window['go']['services']['CalculationService']['IsRobotSelected'](arg1, arg2);
}

export function IsValidIPAddress(arg1) {
  return window['go']['services']['CalculationService']['IsValidIPAddress'](arg1);
}

export function ParseRobotMask(arg1) {
  return window['go']['services']['CalculationService']['ParseRobotMask'](arg1);
}

export function SanitizeVariableName(arg1) {
  return window['go']['services']['CalculationService']['SanitizeVariableName'](arg1);
}

export function ToggleRobotMask(arg1, arg2) {
  return window['go']['services']['CalculationService']['ToggleRobotMask'](arg1, arg2);
}

export function ValidateRobotVarIndexForRobot(arg1, arg2, arg3) {
  return window['go']['services']['CalculationService']['ValidateRobotVarIndexForRobot'](arg1, arg2, arg3);
}
