// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {services} from '../models';

export function HasRobotVarIndexError(arg1:models.Parameter,arg2:Array<models.Parameter>):Promise<boolean>;

export function IsConfigFieldVisible(arg1:string,arg2:Record<string, any>,arg3:string):Promise<boolean>;

export function IsRobotSelected(arg1:number,arg2:number):Promise<boolean>;

export function IsValidIPAddress(arg1:string):Promise<boolean>;

export function ParseRobotMask(arg1:string):Promise<number>;

export function SanitizeVariableName(arg1:string):Promise<string>;

export function ToggleRobotMask(arg1:number,arg2:number):Promise<number>;

export function ValidateRobotVarIndexForRobot(arg1:models.Parameter,arg2:number,arg3:Array<models.Parameter>):Promise<services.RobotVarIndexValidation>;
