// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {context} from '../models';

export function ExportEVToST(arg1:string,arg2:Array<models.Electrovalve>):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;
