// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportEVToST(arg1, arg2) {
  return window['go']['services']['ExportService']['ExportEVToST'](arg1, arg2);
}

export function Startup(arg1) {
  return window['go']['services']['ExportService']['Startup'](arg1);
}
