// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportConfigToFile(arg1) {
  return window['go']['services']['StorageService']['ExportConfigToFile'](arg1);
}

export function ImportConfigFromFile() {
  return window['go']['services']['StorageService']['ImportConfigFromFile']();
}

export function LoadData() {
  return window['go']['services']['StorageService']['LoadData']();
}

export function SaveData(arg1) {
  return window['go']['services']['StorageService']['SaveData'](arg1);
}

export function Startup(arg1) {
  return window['go']['services']['StorageService']['Startup'](arg1);
}
